### ISSUE TITLE
Weird error in SkyModel unit checking via `pyuvsim.simset.initialize_catalog_from_params`

### ISSUE THREAD

**Issue by piyanatk** [RadioAstronomySoftwareGroup/pyradiosky#157]
I am not sure if this issue should be on pyuvsim repo or here. I have been struggling with a weird error, where `pyuvsim.simsetup.initialize_catalog_from_obsparams` fails at  the `run_check` in `sky.source_cuts`, saying that the Stokes array is a `NoneType` and have no unit. 

```python
> Using `pyuvsim.simset.initialize_catalog_from_params`
Traceback (most recent call last):
  File "h1c-idr3-sim-test.py", line 173, in <module>
    simsetup.initialize_catalog_from_params(obs_params)
  File "/lustre/aoc/projects/hera/pkittiwi/miniconda3/envs/pyuvsim_test/lib/python3.8/site-packages/pyuvsim/simsetup.py", line 716, in initialize_catalog_from_params
    sky.source_cuts(**source_select_kwds)
  File "/lustre/aoc/projects/hera/pkittiwi/miniconda3/envs/pyuvsim_test/lib/python3.8/site-packages/pyradiosky/skymodel.py", line 1986, in source_cuts
    skyobj.check(
  File "/lustre/aoc/projects/hera/pkittiwi/miniconda3/envs/pyuvsim_test/lib/python3.8/site-packages/pyradiosky/skymodel.py", line 820, in check
    param_unit = param.value.unit
AttributeError: 'NoneType' object has no attribute 'unit'
```

The skyh5 file was made by @jburba, and is a subset of the GLEAM catalog with a proper unit if you directly read it with pyradiosky. This seemed very strange, so I copied and paste the code in `pyuvsim.simsetup.initialize_catalog_from_obsparams` into a script to make a "homebrew" version of the method, and indeed it ran okay.

I have compiled what I think is a minimum working example in the attached. It still requires access to gygax to grab the skyh5 file (0.6G) and a conda installation. Specifically, to run the test one will have to,

1. Grab `/lustre/aoc/projects/hera/Validation/h1c-idr3-sim-setup/gleam-120.02-127.34MHz-nf-76-pld.skyh5`
2. extract the attached tarball
3. do `source run_test.sh`

The bash script will create a new conda environment called pyuvsim_test and execute the included py script, which has the “homebrew” method. The script will call that function with the included obsparams and the skyh5 file from lustre, and then do the same call again with `pyuvsim.simsetup.initialize_catalog_from_obsparams`. The former works, but the latter will give the unit error above. I have tried this on my laptop, gygax, and ilifu, and got the same error. At this point, I am not really sure if the problem comes from the conda installation or if it is a bug in pyuvsim or pyradiosky.

MWE: [h1c-idr3-sim-test.tar.gz](https://github.com/RadioAstronomySoftwareGroup/pyradiosky/files/7216061/h1c-idr3-sim-test.tar.gz)

**Comment by piyanatk** [comment]
More tests point to a potential bug in the PyPI package of pyuvsim.
